In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv('datasets.csv')

In [8]:
df.head(1)

6  148  72  35  0  33.6  0.627  50  1
0  1   85  66  29  0  26.6  0.351  31  0

In [10]:
df.rename(columns = {'6' : 'Pregnancies' , '148' : 'Glucose' , '72' : 'BloodPressure' , '35' : 'SkinThickness' , '0' : 'Insulin' , '33.6' : 'BMI' , '0.627' : 'DiabetesPedigreeFunction' , '50' : 'Age' , '1' : 'outcome'},inplace =True)

In [11]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            1       85             66             29        0  26.6   
1            8      183             64              0        0  23.3   
2            1       89             66             23       94  28.1   
3            0      137             40             35      168  43.1   
4            5      116             74              0        0  25.6   

   DiabetesPedigreeFunction  Age  outcome  
0                     0.351   31        0  
1                     0.672   32        1  
2                     0.167   21        0  
3                     2.288   33        1  
4                     0.201   30        0

In [12]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   767.000000  767.000000     767.000000     767.000000  767.000000   
mean      3.842243  120.859192      69.101695      20.517601   79.903520   
std       3.370877   31.978468      19.368155      15.954059  115.283105   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   32.000000   
75%       6.000000  140.000000      80.000000      32.000000  127.500000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     outcome  
count  767.000000                767.000000  767.000000  767.000000  
mean    31.990482                  0.471674   33.219035    0.348110  
std      7.889091                  0.331497   11.752296    0.476682  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243500   24.000000    0.000000  
50%     32.000000                  0.371000   29.000000    0.000000  
75%     36.600000                  0.625000   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 767 entries, 0 to 766
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               767 non-null    int64  
 1   Glucose                   767 non-null    int64  
 2   BloodPressure             767 non-null    int64  
 3   SkinThickness             767 non-null    int64  
 4   Insulin                   767 non-null    int64  
 5   BMI                       767 non-null    float64
 6   DiabetesPedigreeFunction  767 non-null    float64
 7   Age                       767 non-null    int64  
 8   outcome                   767 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [15]:
df.duplicated().sum()   # no duplicate value is present

0

In [17]:
df['outcome'].value_counts()    # data is not so biased

0    500
1    267
Name: outcome, dtype: int64

In [18]:
from sklearn.model_selection import train_test_split
X = df.drop(columns = ['outcome']);
y = df['outcome']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 1)

In [19]:
X.shape

(767, 8)

In [20]:
y.shape

(767,)

In [21]:
X.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            1       85             66             29        0  26.6   
1            8      183             64              0        0  23.3   
2            1       89             66             23       94  28.1   
3            0      137             40             35      168  43.1   
4            5      116             74              0        0  25.6   

   DiabetesPedigreeFunction  Age  
0                     0.351   31  
1                     0.672   32  
2                     0.167   21  
3                     2.288   33  
4                     0.201   30

In [22]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [23]:
X_train_scaled

array([[ 1.49469849,  0.70529254,  0.57078307, ...,  0.73884819,
         0.55721449,  0.58496446],
       [ 1.7896921 ,  0.20300462, -0.37203436, ...,  1.1680149 ,
        -0.05569033,  0.4142512 ],
       [-1.16024406, -0.26789031,  0.57078307, ...,  1.55816646,
        -0.91250626, -0.52467177],
       ...,
       [ 0.01973041,  0.20300462,  0.88505555, ...,  0.37470673,
        -0.71237407, -0.8660983 ],
       [ 0.90471125,  1.83544037,  0.78029806, ...,  0.47874715,
         0.39773416,  1.52388743],
       [-0.57025683, -1.02132219, -0.05776188, ...,  0.77786334,
         0.13818772, -0.52467177]])

In [24]:
X_test_scaled

array([[ 0.31472402,  1.0192225 ,  0.78029806, ...,  0.8428886 ,
         0.50092731,  0.07282466],
       [-1.16024406,  0.07743264,  1.40884301, ..., -1.26392981,
        -0.61543504, -1.03681157],
       [ 2.37967934, -0.04813934,  0.46602558, ..., -0.74372773,
        -0.62481624,  2.4628104 ],
       ...,
       [ 0.90471125,  0.92504351,  0.98981304, ...,  2.31245947,
        -0.38090514,  0.24353793],
       [ 0.31472402,  0.42275559,  0.67554056, ..., -4.1900665 ,
         0.56659569,  3.06030683],
       [ 0.01973041, -1.02132219, -3.61951661, ..., -0.54865195,
         0.47278373, -0.18324524]])

In [28]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense


In [29]:
model = Sequential()
#1st layer 8 input so input_dim = 8 and activation function which is used is relu
# 12 repersent number of nodes in the hidden layer 1
model.add(Dense(12,input_dim = 8,activation = 'relu'))
#2nd layer ....for next layer 8 nodes is present
model.add(Dense(8,activation = 'relu'))
model.add(Dense(1,activation = 'relu'))


In [30]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 12)                108       
                                                                 
 dense_1 (Dense)             (None, 8)                 104       
                                                                 
 dense_2 (Dense)             (None, 1)                 9         
                                                                 
Total params: 221 (884.00 Byte)
Trainable params: 221 (884.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [32]:
model.compile(loss = 'binary_crossentropy',optimizer = 'Adam')  # it is a binary classification so binary_crossentropy

In [34]:
model.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6334
Epoch 2/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6266
Epoch 3/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6195
Epoch 4/100
20/20 [==============================] - 0s 1ms/step - loss: 0.6137
Epoch 5/100
20/20 [==============================] - 0s 1ms/step - loss: 0.6087
Epoch 6/100
20/20 [==============================] - 0s 1ms/step - loss: 0.5839
Epoch 7/100
20/20 [==============================] - 0s 1ms/step - loss: 0.5570
Epoch 8/100
20/20 [==============================] - 0s 1ms/step - loss: 0.5522
Epoch 9/100
20/20 [==============================] - 0s 1ms/step - loss: 0.5469
Epoch 10/100
20/20 [==============================] - 0s 1ms/step - loss: 0.5437
Epoch 11/100
20/20 [==============================] - 0s 1ms/step - loss: 0.5403
Epoch 12/100
20/20 [==============================] - 0s 1ms/step - loss: 0.5365
Epoch 13/100
20/20 [=================

In [39]:
y_log = model.predict(X_test_scaled)
y_log

5/5 [==============================] - 0s 2ms/step


array([[0.7519184 ],
       [0.        ],
       [0.2578749 ],
       [0.        ],
       [0.        ],
       [0.4769672 ],
       [0.        ],
       [0.29938754],
       [0.24932726],
       [0.        ],
       [0.5114506 ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.        ],
       [0.51945984],
       [0.47337812],
       [0.21983501],
       [0.06966104],
       [0.        ],
       [0.        ],
       [0.37427896],
       [0.35403153],
       [0.27913287],
       [0.15312882],
       [0.        ],
       [0.19538067],
       [0.        ],
       [0.        ],
       [0.68117636],
       [0.27682766],
       [0.3560852 ],
       [0.3334451 ],
       [0.6751725 ],
       [0.        ],
       [0.9112656 ],
       [0.        ],
       [0.56435335],
       [0.70883334],
       [0.12545408],
       [0.2840809 ],
       [0.16228501],
       [0.3710733 ],
       [0.27439824],
       [0.        ],
       [0.15040009],
       [0.2165113 ],
       [0.040

In [36]:
y_pred = np.where(y_log>0.5,1,0)

In [38]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7727272727272727