In [50]:
import pandas as pd
import numpy as np

In [51]:
df = pd.read_csv('datasets.csv')

In [52]:
df.head(1)

6  148  72  35  0  33.6  0.627  50  1
0  1   85  66  29  0  26.6  0.351  31  0

In [53]:
df.rename(columns = {'6' : 'Pregnancies' , '148' : 'Glucose' , '72' : 'BloodPressure' , '35' : 'SkinThickness' , '0' : 'Insulin' , '33.6' : 'BMI' , '0.627' : 'DiabetesPedigreeFunction' , '50' : 'Age' , '1' : 'outcome'},inplace =True)

In [54]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            1       85             66             29        0  26.6   
1            8      183             64              0        0  23.3   
2            1       89             66             23       94  28.1   
3            0      137             40             35      168  43.1   
4            5      116             74              0        0  25.6   

   DiabetesPedigreeFunction  Age  outcome  
0                     0.351   31        0  
1                     0.672   32        1  
2                     0.167   21        0  
3                     2.288   33        1  
4                     0.201   30        0

In [55]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   767.000000  767.000000     767.000000     767.000000  767.000000   
mean      3.842243  120.859192      69.101695      20.517601   79.903520   
std       3.370877   31.978468      19.368155      15.954059  115.283105   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   32.000000   
75%       6.000000  140.000000      80.000000      32.000000  127.500000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     outcome  
count  767.000000                767.000000  767.000000  767.000000  
mean    31.990482                  0.471674   33.219035    0.348110  
std      7.889091                  0.331497   11.752296    0.476682  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243500   24.000000    0.000000  
50%     32.000000                  0.371000   29.000000    0.000000  
75%     36.600000                  0.625000   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 767 entries, 0 to 766
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               767 non-null    int64  
 1   Glucose                   767 non-null    int64  
 2   BloodPressure             767 non-null    int64  
 3   SkinThickness             767 non-null    int64  
 4   Insulin                   767 non-null    int64  
 5   BMI                       767 non-null    float64
 6   DiabetesPedigreeFunction  767 non-null    float64
 7   Age                       767 non-null    int64  
 8   outcome                   767 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [57]:
df.duplicated().sum()   # no duplicate value is present

0

In [58]:
df['outcome'].value_counts()    # data is not so biased

0    500
1    267
Name: outcome, dtype: int64

In [59]:
from sklearn.model_selection import train_test_split
X = df.drop(columns = ['outcome']);
y = df['outcome']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 1)

In [60]:
X.shape

(767, 8)

In [61]:

y.shape

(767,)

In [62]:
X.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            1       85             66             29        0  26.6   
1            8      183             64              0        0  23.3   
2            1       89             66             23       94  28.1   
3            0      137             40             35      168  43.1   
4            5      116             74              0        0  25.6   

   DiabetesPedigreeFunction  Age  
0                     0.351   31  
1                     0.672   32  
2                     0.167   21  
3                     2.288   33  
4                     0.201   30

In [63]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [64]:
X_train_scaled

array([[ 1.49469849,  0.70529254,  0.57078307, ...,  0.73884819,
         0.55721449,  0.58496446],
       [ 1.7896921 ,  0.20300462, -0.37203436, ...,  1.1680149 ,
        -0.05569033,  0.4142512 ],
       [-1.16024406, -0.26789031,  0.57078307, ...,  1.55816646,
        -0.91250626, -0.52467177],
       ...,
       [ 0.01973041,  0.20300462,  0.88505555, ...,  0.37470673,
        -0.71237407, -0.8660983 ],
       [ 0.90471125,  1.83544037,  0.78029806, ...,  0.47874715,
         0.39773416,  1.52388743],
       [-0.57025683, -1.02132219, -0.05776188, ...,  0.77786334,
         0.13818772, -0.52467177]])

In [65]:
X_test_scaled

array([[ 0.31472402,  1.0192225 ,  0.78029806, ...,  0.8428886 ,
         0.50092731,  0.07282466],
       [-1.16024406,  0.07743264,  1.40884301, ..., -1.26392981,
        -0.61543504, -1.03681157],
       [ 2.37967934, -0.04813934,  0.46602558, ..., -0.74372773,
        -0.62481624,  2.4628104 ],
       ...,
       [ 0.90471125,  0.92504351,  0.98981304, ...,  2.31245947,
        -0.38090514,  0.24353793],
       [ 0.31472402,  0.42275559,  0.67554056, ..., -4.1900665 ,
         0.56659569,  3.06030683],
       [ 0.01973041, -1.02132219, -3.61951661, ..., -0.54865195,
         0.47278373, -0.18324524]])

In [66]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout


In [67]:
model = Sequential()
#1st layer 8 input so input_dim = 8 and activation function which is used is relu
# 12 repersent number of nodes in the hidden layer 1
model.add(Dense(12,input_dim = 8,activation = 'relu'))
#2nd layer ....for next layer 8 nodes is present
model.add(Dense(8,activation = 'relu'))
model.add(Dense(1,activation = 'sigmoid'))


In [68]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 12)                108       
                                                                 
 dense_7 (Dense)             (None, 8)                 104       
                                                                 
 dense_8 (Dense)             (None, 1)                 9         
                                                                 
Total params: 221 (884.00 Byte)
Trainable params: 221 (884.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [69]:
model.compile(loss = 'binary_crossentropy',optimizer = 'Adam')  # it is a binary classification so binary_crossentropy

In [70]:
model.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
20/20 [==============================] - 1s 2ms/step - loss: 0.7360
Epoch 2/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6861
Epoch 3/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6490
Epoch 4/100
20/20 [==============================] - 0s 2ms/step - loss: 0.6220
Epoch 5/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5988
Epoch 6/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5792
Epoch 7/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5628
Epoch 8/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5481
Epoch 9/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5364
Epoch 10/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5270
Epoch 11/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5197
Epoch 12/100
20/20 [==============================] - 0s 2ms/step - loss: 0.5134
Epoch 13/100
20/20 [=================

In [71]:
y_log = model.predict(X_test_scaled)
y_log

5/5 [==============================] - 0s 2ms/step


array([[4.30756837e-01],
       [6.84848847e-03],
       [2.81669647e-01],
       [2.55437475e-02],
       [1.76799558e-02],
       [4.02314454e-01],
       [1.03916097e-02],
       [4.95793164e-01],
       [2.60596961e-01],
       [2.49081338e-03],
       [4.31760252e-01],
       [1.07203505e-03],
       [3.14803869e-02],
       [3.75894643e-02],
       [3.50912213e-02],
       [3.38463873e-01],
       [3.53268296e-01],
       [4.33964401e-01],
       [2.01843083e-01],
       [5.20496853e-02],
       [2.49369070e-03],
       [4.26016182e-01],
       [4.76605088e-01],
       [3.32448691e-01],
       [8.10218453e-02],
       [1.07534742e-02],
       [1.54035240e-01],
       [1.10444501e-02],
       [3.41288336e-02],
       [6.76170111e-01],
       [5.58460891e-01],
       [1.18069388e-01],
       [2.70574570e-01],
       [5.59728444e-01],
       [7.30789965e-03],
       [6.83832765e-01],
       [4.32554334e-02],
       [4.14198726e-01],
       [7.62242913e-01],
       [2.47158334e-01],


In [72]:
y_pred = np.where(y_log>0.5,1,0)

In [73]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8181818181818182